### PR TITLE
Fixed Wayland regression

### PR DESCRIPTION
**Pull request by danilown**
There might have been a mistake. Without the Wayland socket, Joplin won't start at all under Wayland.

### CODE REVIEW

**Comment by catsout** [comment]
x11 works with xwayland.

**Comment by danilown** [comment]
That's correct. But why use Xwayland if it can run on Wayland natively? The biggest problem is with fractional scaling. When running on Xwayland Electron apps get blurry, see https://github.com/microsoft/vscode/issues/72759#issue-436121667.

**Comment by catsout** [comment]
Because electron is default x11.  
I has tried default wayland, but it's broken on somebody's system.

**Comment by danilown** [comment]
But broken in which way? Simply doesn't open? There is a mouse glitch, in which the mouse cursor is ~10% visible, but in my commit, there is also a fix for that. I've used the same solution as Signal, and it seems to work.

**Comment by danilown** [comment]
What is blocking this from being merged?

**Comment by catsout** [comment]
I think it's better to keep the same behavior as joplin appimage.

**Comment by deepwell** [comment]
I'm eagerly awaiting this PR to be merged now that electron has been updated with proper Wayland protocol support. Joplin, without Wayland protocol support, is pretty unusable with fractional scaling (blurry fonts).

**Comment by danilown** [comment]
Hey @deepwell , the support is already implemented but disabled by default. You can enable it with [Flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal) by checking the "Wayland windowing system" toggle or by running the command below: 

```bash
flatpak override -u net.cozic.joplin_desktop --socket=wayland
```

**Pull request closed without merging**
