### PR TITLE
Fix Joplin Issue #6079

### PR DESCRIPTION
**Pull request by BeatLink**
https://github.com/laurent22/joplin/issues/6079

Also this issue in this repo

https://github.com/flathub/net.cozic.joplin_desktop/issues/6

### CODE REVIEW

**Comment by BeatLink** [comment]
@catsout perhaps you could take a look if you have the time?

**Comment by catsout** [comment]
It's not ok to be merged.  
`persist` is only suitable for files that will never be shared with other application  
But joplin needs external editor to edit the note in `persist`, which is impossible as external editor get the path `~/.config/...`(in sandbox not in outside), they can't see files in outside's `~/.config/..`

**Comment by catsout** [comment]
If joplin supports [xdg base dir](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), we don't need to do anything.  
To be compatible with current users, we can add a soft link from xdg dir to `~/.config/..` to not break their experience and new users use the default xdg dir

**Comment by sequencerr** [comment]
Ok, so joplin supports symlinks to specific directories in it's home dir, Can somebody please explain me why it's impossible to update flatpkg recipe to create symlinks there, despite joplin doesn't support all xdg env vars? @BeatLink

**Pull request closed without merging**
