### PR TITLE
Update metainfo.xml with bugtracker URL

### PR DESCRIPTION
**Pull request by FHEK789**

### CODE REVIEW

**Comment by tinywrkb** [comment]
The Flatpak package is not officially maintained by its developer so I'm not sure about having the Flathub app page linking to the upstream bug tracker and spamming upstream with unrelated bug reports.  
I say leave it as it is and let the user figure out if this is a Flatpak related bug so should be reported here or a generic one so it should be reported upstream.  
@catsout can give a final answer about this.  
CC @laurent22

**Comment by FHEK789** [comment]
ping! :)

**Comment by catsout** [comment]
I will merge it when joplin's new version released.

**Comment by laurent22** [comment]
Sorry, I missed that but I would indeed prefer if the package didn't link to our bug tracker. We don't have the resources and sometimes knowledge to support the flatpak package, so I would appreciate if you could remove the URL. If it turns out a bug is indeed an upstream one you're of course welcome to report it over there, and link to the report here.

**Comment by catsout** [comment]
Reverted.

**Comment by hutson** [comment]
Hopefully in the future the _transfer issue_ feature (https://docs.github.com/en/issues/tracking-your-work-with-issues/managing-issues/transferring-an-issue-to-another-repository#transferring-an-open-issue-to-another-repository) can be used to help facilitate early triaging on this repository, with easier transfer of upstream-related issues to the `joplin` repository.

@catsout would you consider re-submitting a change that would point the `bugtracker` field to this repository's issue tracker?

If managing reports on this repository is a burden, could issue templates help mitigate the costs by ensuring users provide relevant/actionable information? (https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

**Comment by catsout** [comment]
@hutson No, I'd like to keep the things as before.

**Pull request merged**
