### PR TITLE
Update to 2.3.3

### PR DESCRIPTION
**Pull request by catsout**

### CODE REVIEW

**Comment by catsout** [comment]
bot, build net.cozic.joplin_desktop

**Comment by catsout** [comment]
@nedrichards
The flathub bot will stuck at downloading sources.

**Comment by catsout** [comment]
@barthalion 
The flathub bot will stuck at downloading sources.

**Comment by tinywrkb** [comment]
@catsout 

Try adding `sed -i 's#git+ssh://git@#https://#' generated-sources.json` to the workflow.

**Comment by tinywrkb** [comment]
Post the `Replace 'git+ssh' to http` commit  and with the following the build is failing in a bit later while running `git ls-remote -h -t` due to the fact network is not available.

```
diff --git a/net.cozic.joplin_desktop.yml b/net.cozic.joplin_desktop.yml
index f1315ef..74c0fef 100644
--- a/net.cozic.joplin_desktop.yml
+++ b/net.cozic.joplin_desktop.yml
@@ -61,6 +61,7 @@ modules:
         npm_config_no_save: 'true'
         npm_config_loglevel: silly
     build-commands:
+      - sed -i 's#git+ssh://git@\(github.com/laurent22\)#git://\1#' packages/{app-cli,lib,renderer}/package-lock.json
       - npm install
       # generateSha512.js require appimage build, need touch it
       # If no it will cause electron-builder failed without error message even set debug!
```

I don't know if there's a way to disable the `git ls-remote`, so upstream might need to switch to a tarball source instead of git.  
The alternative is to regenerate the `package-lock.json` during the auto-update workflow, add them here to the repo, and copy over the upstream's ones before running `npm install` when building the package.

Another reason why upstream should consider switching to tarballs instead of git is [this issue](https://github.com/npm/cli/issues/2610).

/ping @laurent22

**Comment by laurent22** [comment]
@tinywrkb, I'm not familiar with these problems. What's causing an issue in Joplin repo?

**Comment by catsout** [comment]
> Post the Replace 'git+ssh' to http commit and with the following the build is failing in a bit later while running git ls-remote -h -t due to the fact network is not available.

npm find a package with git url:`https://github.com`, but there is no network.  
The `flatpak-builder-tools` will create some script to replace this git url to local `git+file://` url   
But seems the npm change it's behavior, which make the script do not replace the git url  
Need to write extra code on my fork of `flatpak-builder-tools`

**Comment by catsout** [comment]
```
WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
```

**Comment by tinywrkb** [comment]
@laurent22 as @catsout pointed out, there are some difficulties of building in offline mode when there are node modules with git sources. To work around them, some changes are needed to be made to the Flatpak packaging helpers, `flatpak-builder-tools`.  
These issues could be avoided if only tarball sources were used, at least for tagged releases, though it's better to fix `flatpak-builder-tools`.

**Comment by catsout** [comment]
@tinywrkb
I think the git source has been fixed by https://github.com/flathub/net.cozic.joplin_desktop/commit/a1dcedb89eeee4e43f4cf06d23c4972d1242ff86  
The build now failed with `fs-extra`, which may caused by the new lockfile version.Need more test to find why npm requires to fetch fresh package.

**Comment by catsout** [comment]
Seems like it's the same issue as https://github.com/laurent22/joplin/issues/4478  
Just patch to same version.

**Pull request merged**
